/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SurveySurveySlugRouteImport } from './routes/survey.$surveySlug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin/surveys.index'
import { Route as SurveySurveySlugThankYouRouteImport } from './routes/survey.$surveySlug.thank-you'
import { Route as AdminSurveysNewRouteImport } from './routes/admin/surveys.new'
import { Route as AdminSurveysSurveyIdRouteImport } from './routes/admin/surveys.$surveyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SurveySurveySlugRoute = SurveySurveySlugRouteImport.update({
  id: '/survey/$surveySlug',
  path: '/survey/$surveySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SurveySurveySlugThankYouRoute =
  SurveySurveySlugThankYouRouteImport.update({
    id: '/thank-you',
    path: '/thank-you',
    getParentRoute: () => SurveySurveySlugRoute,
  } as any)
const AdminSurveysNewRoute = AdminSurveysNewRouteImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSurveysSurveyIdRoute = AdminSurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/survey/$surveySlug': typeof SurveySurveySlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/survey/$surveySlug/thank-you': typeof SurveySurveySlugThankYouRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/survey/$surveySlug': typeof SurveySurveySlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/survey/$surveySlug/thank-you': typeof SurveySurveySlugThankYouRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/survey/$surveySlug': typeof SurveySurveySlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/survey/$surveySlug/thank-you': typeof SurveySurveySlugThankYouRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/analytics'
    | '/admin/users'
    | '/survey/$surveySlug'
    | '/admin/'
    | '/admin/surveys/$surveyId'
    | '/admin/surveys/new'
    | '/survey/$surveySlug/thank-you'
    | '/admin/surveys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/users'
    | '/survey/$surveySlug'
    | '/admin'
    | '/admin/surveys/$surveyId'
    | '/admin/surveys/new'
    | '/survey/$surveySlug/thank-you'
    | '/admin/surveys'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/analytics'
    | '/admin/users'
    | '/survey/$surveySlug'
    | '/admin/'
    | '/admin/surveys/$surveyId'
    | '/admin/surveys/new'
    | '/survey/$surveySlug/thank-you'
    | '/admin/surveys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SurveySurveySlugRoute: typeof SurveySurveySlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/survey/$surveySlug': {
      id: '/survey/$surveySlug'
      path: '/survey/$surveySlug'
      fullPath: '/survey/$surveySlug'
      preLoaderRoute: typeof SurveySurveySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/survey/$surveySlug/thank-you': {
      id: '/survey/$surveySlug/thank-you'
      path: '/thank-you'
      fullPath: '/survey/$surveySlug/thank-you'
      preLoaderRoute: typeof SurveySurveySlugThankYouRouteImport
      parentRoute: typeof SurveySurveySlugRoute
    }
    '/admin/surveys/new': {
      id: '/admin/surveys/new'
      path: '/surveys/new'
      fullPath: '/admin/surveys/new'
      preLoaderRoute: typeof AdminSurveysNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/surveys/$surveyId': {
      id: '/admin/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/admin/surveys/$surveyId'
      preLoaderRoute: typeof AdminSurveysSurveyIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSurveysSurveyIdRoute: typeof AdminSurveysSurveyIdRoute
  AdminSurveysNewRoute: typeof AdminSurveysNewRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSurveysSurveyIdRoute: AdminSurveysSurveyIdRoute,
  AdminSurveysNewRoute: AdminSurveysNewRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SurveySurveySlugRouteChildren {
  SurveySurveySlugThankYouRoute: typeof SurveySurveySlugThankYouRoute
}

const SurveySurveySlugRouteChildren: SurveySurveySlugRouteChildren = {
  SurveySurveySlugThankYouRoute: SurveySurveySlugThankYouRoute,
}

const SurveySurveySlugRouteWithChildren =
  SurveySurveySlugRoute._addFileChildren(SurveySurveySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SurveySurveySlugRoute: SurveySurveySlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
